Fix ActsAsEditable errors when reloading classes in development
Steps to reproduce:
$ rails c
>> Project.first
>> reload!
>> Project.first
Reloading...
ArgumentError: A copy of ActsAsEditable::ClassMethods has been removed from the module tree but is still active!
from activesupport-4.1.7/lib/active_support/dependencies.rb:465:in `load_missing_constant'